language: java
jdk:
- oraclejdk8
before_deploy:
- "./gradlew generatePomFileForMavenPublication"
- "./gradlew --stacktrace copyBintrayTemplate"
deploy:
- provider: s3
  on:
    all_branches: true
  upload-dir: output
  bucket: cromulence.travis.datawrapper
  region: eu-west-2
  skip_cleanup: true
  access_key_id: AKIAJAAE254CVSJG4RTQ
  secret_access_key:
    secure: UgwyQnAH0Q2jBfEwX9HFCzv5vRDAfZ/ZZ1M6GhVDaJKdWMXj7cwLwcAtAbFJ1kOhPKBvjAZaK1yg4cNq30SgUalX9MEFz7G1jQu4ye8nP6GfiK73uTxay5VSkGEHorwUEExDAoBwv+bBaLwhavGbSyHd+cELf7Xip9I9EW3BR0OzpM5280MbimgXOP04O+QmtVpQTKxm03VasiOWkd4s+rSRe8s5VqPF/wNESkc+Tb4x4MyYCpwkGs5a1NhFehVNdgpV7AyOXto88guOfyaDU46GO3HYHa3440Uvq+N06RvZpppvPB3EQS24vQy7RIHSQgYGkYeLgio2Q9WNJ23CGvHmfWKlfnECCFO8ID5qaftulgsezLvmEpG0FX2rWPZ72DOEKiXUzCZotkColpzbOMq5+1Yi+lnqtiAvPaII4evvHJFIaiduEkp+mLaqFhialhMNFhE9XzJuqbIxE3Q6v3OW66WO9kvN8GzkgbEauTOzkH26rKfzRPX9AFghSJM9qRCn37e9sXAjVajXCv9GS9fRZN9D15UtGLTX7cFedub+Dom9U2XyRAYm29mLitwqyb1Q3wCXJwO7NUF8yQb6G5o9FDJF7E1bN12xtw7AkFfZP+5aL1U0qGWC3wMzbGg1rzTrbndghLGh1eQQLbfqqwuKdGMuSIUpDV2av66yYhk=
- provider: bintray
  on:
    tags: true
  skip_cleanup: true
  file: build/bintray.json
  user: cromulence
  key:
    secure: DSdOofeDz6f0yD6kaReUymAJpOtwu3HZVVQtbIE2dswZTrhmWKULVr4jSB+gtdbGhLEmR+c9+BBB4eukNeo2dg6SlP1U4j/xl+GMwrxEl9COzTuBhmbEUL4dHhJ0ODTH083klVs0Q2R74bao14W7FaMLdJpMmD9W03DjKMNLte7t3ZipScQ+9UdcKi79XullqpjX73fgMf73v3JO7H1sJA1gtFrN/68C5wCY/FsbJmIGvDAg8/F7PXDAOUUZX5DMqSnNN0is6twbTS0TAlXC5yNxF3Pnc/jrgei1W5qMEXStYLJomKa5RYqaO3f6D6AqqpbtHe5SEuYkyxo8AX1xiIL+7LlzWxhtaOVM12d8WKpsYvL/LnKTmwPFhJ3atqgleRcqN46lrSWzT3njrwBkgYqLAkgw9WtrWW+StVCLgYZeSNDrwWgimzvE1MWx3QcbGcgJMCkVPMgnR70e9TKkXoIS6S8YWQzpTLKZ5zUA0dtZksRTMZeeh8H+AvX3mAaVOIw0I10pbd5v4edbgJy4Tkd9Q4cQagPAwQuy4SDhKwu0gPPku+R6URh3O75SzxcL2pbajksTw3j+m7ZR+RfTLac5W6bXIDKAIG4pEc2Ln+6QTfRzrN5oZkrOzcXg+JLBySuB9w32SE+By0kdb7IUBogRKBPgByeC/UUXzWvLrhc=
  dry-run: false
