language: java
jdk:
- oraclejdk8
before_deploy:
- "./gradlew generatePomFileForMavenPublication"
- "./gradlew --stacktrace copyBintrayTemplate"
deploy:
- provider: s3
  on:
    all_branches: true
  upload-dir: output
  bucket: cromulence.travis.datawrapper
  region: eu-west-2
  skip_cleanup: true
  access_key_id: AKIAJAAE254CVSJG4RTQ
  secret_access_key:
    secure: UgwyQnAH0Q2jBfEwX9HFCzv5vRDAfZ/ZZ1M6GhVDaJKdWMXj7cwLwcAtAbFJ1kOhPKBvjAZaK1yg4cNq30SgUalX9MEFz7G1jQu4ye8nP6GfiK73uTxay5VSkGEHorwUEExDAoBwv+bBaLwhavGbSyHd+cELf7Xip9I9EW3BR0OzpM5280MbimgXOP04O+QmtVpQTKxm03VasiOWkd4s+rSRe8s5VqPF/wNESkc+Tb4x4MyYCpwkGs5a1NhFehVNdgpV7AyOXto88guOfyaDU46GO3HYHa3440Uvq+N06RvZpppvPB3EQS24vQy7RIHSQgYGkYeLgio2Q9WNJ23CGvHmfWKlfnECCFO8ID5qaftulgsezLvmEpG0FX2rWPZ72DOEKiXUzCZotkColpzbOMq5+1Yi+lnqtiAvPaII4evvHJFIaiduEkp+mLaqFhialhMNFhE9XzJuqbIxE3Q6v3OW66WO9kvN8GzkgbEauTOzkH26rKfzRPX9AFghSJM9qRCn37e9sXAjVajXCv9GS9fRZN9D15UtGLTX7cFedub+Dom9U2XyRAYm29mLitwqyb1Q3wCXJwO7NUF8yQb6G5o9FDJF7E1bN12xtw7AkFfZP+5aL1U0qGWC3wMzbGg1rzTrbndghLGh1eQQLbfqqwuKdGMuSIUpDV2av66yYhk=
- provider: bintray
  on:
    tags: true
  file: output/bintray.json
  user: cromulence
  key:
    secure: MzQD1yLmR/A/bGh82g0ljTFTgnBZA0qLOFZxur9FN/RUERv23cHFqhXLj3ct/Kk652CBe0DpZJpUiuV208o+gtOrN2ZV+L4SwJGRljJCGcg/7LsYRfkmF8IiBz682Rlo+PTkVnJJ3a/5d2uTgORcleerIncg9csZK3UPNIxQeZVXJYDNaGpVIkHeoZ+uiZjGf/9ud9JGBs+W5pPSX3pD01k0OzRi/mMetTnGK6XWvPIvB4s5oIwpLrylRqZK1Sc+GQf/wmHTP4ZXPhBRbqsZ4pQLN2NScRnAeMLO6QmfgH9YHx+8tojyfLWSajXCuEVQWU9EFZo135I+Ys4OXUCGKAOqcZvYX28BNlOsq12jdQscQFOKvMIEmp/3ujbIBCpID5dOmbx58eUJ0RtO/fNpaltBqKxGAcBxTu6VHyeTAqHEcgHkExWV09UutK7djNLUJqnVablaZ88hrcu7BYINkncmWNOwZB+xXKC5ZGK7sKSVbFAMxV5sCvgQiE2vzSVIVYxn87gn7J1tt4YpVSGnvCeUx12nB1kadgP/WOu7XMgjs6DQbo41Ee9ucE8rITCFXjdEvcwUkuQieyWhme/ibA5SP/C9L6cdqi9L8fW85x1ZU12NrCHah21cWv/ifW3CsthB6Pjp/ZX70uW/EMwu54V74WMmAHoNU67HybZ/h88=
  dry-run: false
